spring:
  data:
    mongodb:
      database: post
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb://127.0.0.1:27017

#server:
#  port: 443
#
#  ssl:
#    key-store: classpath:local_ssl.p12
#    key-store-password: localkey
#    key-store-type: PKCS12
#    key-alias: baeldung